sudo: required
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c "create user sessiontest with password 'sessiontest';" -U postgres
  - psql -c "create database sessiontest;" -U postgres
  - psql -c "grant all on database sessiontest to sessiontest;" -U postgres
language: java
jdk:
  - oraclejdk8
