CREATE TABLE SPRING_SESSION_ALT (
	SESSION_ID1 BIGINT NOT NULL,
	SESSION_ID2 BIGINT NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_ALT_PK PRIMARY KEY (SESSION_ID1, SESSION_ID2)
);

CREATE INDEX SPRING_SESSION_ALT_IX2 ON SPRING_SESSION_ALT (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_ALT_IX3 ON SPRING_SESSION_ALT (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ALT_ATTRIBUTES (
	SESSION_ID1 BIGINT NOT NULL,
	SESSION_ID2 BIGINT NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ALT_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID1, SESSION_ID2, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ALT_ATTRIBUTES_FK FOREIGN KEY (SESSION_ID1, SESSION_ID2) REFERENCES SPRING_SESSION_ALT 
	ON DELETE CASCADE ON UPDATE CASCADE
);
